import Head from "next/head";
import styles from "@styles/pages/BecomeALugger.module.scss";
import fonts from "@styles/base/fonts.module.scss";
import { Calculator } from "@components";

export default function BecomeALugger() {
  return (
    <>
      <Head>
        <title>Become a Lugger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={fonts.title}>
            Become a Lugger. <br></br>
            You could earn
          </h1>
          <Calculator />
        </div>
      </main>
    </>
  );
}
