import Head from "next/head";
import styles from "@styles/pages/Home.module.scss";
import { Stars, Review } from "@components";
import reviews from "@data/reviews";
import { ReviewProps } from "@types";

export default function Home() {
  return (
    <>
      <Head>
        <title>Become a Lugger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}></main>
    </>
  );
}
