import Head from "next/head";
import styles from "@styles/pages/Reviews.module.scss";
import fonts from "@styles/base/fonts.module.scss";
import { Stars, Review } from "@components";
import reviews from "@data/reviews";
import { ReviewProps } from "@types";
import { Logo } from "@components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Become a Lugger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Logo />
        <div className={styles.titleContainer}>
          <Stars />
          <h1 className={fonts.title}>Over 100,000 5-star moves</h1>
        </div>
        <div className={styles.grid}>
          {reviews.map((item: ReviewProps) => {
            return (
              <Review
                key={item.name}
                name={item.name}
                image={item.image}
                activity={item.activity}
                text={item.text}
              />
            );
          })}
        </div>
      </main>
    </>
  );
}
